# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Timings CI - test

'on':
  push:
    branches:
    - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x, 18.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, build, and run tests
      id: npm_test
      run: |
        npm ci
        npm test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: coverage/cobertura-coverage.xml
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Semantic Release Dry-run
      uses: cycjimmy/semantic-release-action@v3
      id: semantic
      with:
        branch: ${{ steps.extract_branch.outputs.branch }}
        dry_run: true
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
          @semantic-release/npm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
